version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper-bithumb2
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: kafka-bithumb2
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  mongo:
    image: "mongo:4.4.3"
    container_name: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mongo