version: "3"
services:
  redis:
    image: redis:alpine
    command: redis-server --requirepass root --port 6379
    container_name: redis6379
    hostname: redis6379
    labels:
      - "name=redis"
      - "mode=standalone"
    ports:
      - 6379:6379

  app:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - redis

